/* When the user clicks on the button,
            toggle between hiding and showing the dropdown content */
function closeSelector() {
    document.getElementById("direccionDropdown").classList.toggle("show");
}

function filterFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("direccion");
    filter = input.value.toUpperCase();
    div = document.getElementById("direccionDropdown");
    a = div.getElementsByTagName("div");
    for (i = 0; i < a.length; i++) {
        txtValue = a[i].textContent || a[i].innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
            a[i].style.display = "";
        } else {
            a[i].style.display = "none";
        }
    }
}

let address
function selectedAddress(direc) {
    address = direc
    console.log(address)
    closeSelector()
}


const direcciones = ["Lomas del Vergel, Monterrey",
"Samsara, García",
"Bosques de San José, Santiago",
"Santiago",
"El Barro, Santiago",
"Valle la Rioja, Apodaca",
"Futuro Nogalar Sect 1, San Nicolás de los Garza",
"Cima del Bosque, Monterrey",
"Paso Del Águila, Monterrey",
"Benito Juárez Centro, Juárez",
"San Antonio, Juárez",
"San Antonio, Allende",
"Privalia Cumbres, García",
"Lomas Palmeira, García",
"Cuauhtémoc, San Nicolás de los Garza",
"Valle de Cumbres Premier, García",
"Fuentes del Valle, San Pedro Garza García",
"Rincón de las Huertas, Santa Catarina",
"Arezzo Residencial, García",
"El Uro, Monterrey",
"Real Del Valle, Santa Catarina",
"Residencial Céntrika, Monterrey",
"Montenova, García",
"Las Cruces Club de Golf, Apodaca",
"Hacienda Mitras, Monterrey",
"Catujanes, Monterrey",
"Las Lomas Sector Jardines, García",
"La Fama, Santa Catarina",
"Monterrey",
"Gran Reserva, García",
"La Joya, Monterrey",
"Chapultepec, San Nicolás de los Garza",
"2 Ríos, Guadalupe",
"Loma Bonita, Monterrey",
"García",
"Cumbres Elite Premier, García",
"Flor de Piedra, Monterrey",
"La Toscana, Monterrey",
"Valle de Cumbres, García",
"Los Rodriguez, Santiago",
"Cumbres Elite, Monterrey",
"Colinas de San Jerónimo, Monterrey",
"Santiago Centro, Santiago",
"Provivienda de Guadalupe, Guadalupe",
"La Cima, San Pedro Garza García",
"Centro, Monterrey",
"Cerradas Cumbres, Monterrey",
"Paseo de Acueducto Juárez, Juárez",
"Villa Montaña, San Pedro Garza García",
"Las Águilas, Guadalupe",
"San Genaro 1er Sector, Cadereyta Jiménez",
"Sierra Alta 1a Etapa, Monterrey",
"Lomas de San Martín, Pesquería",
"Valle Del Campestre, San Pedro Garza García",
"Murano, García",
"Cumbres, Monterrey",
"Sierra Alta 2a Etapa, Monterrey",
"Yerbaniz, Santiago",
"Pedregal La Silla, Monterrey",
"Carolco, Monterrey",
"San Jose, Juárez",
"Pablo Santos, Sabinas Hidalgo",
"Los Cristales, Monterrey",
"Valle de Cristal, Monterrey",
"Fraccionamiento Espacio Cumbres, Monterrey",
"Granadas de Laderas, Monterrey",
"Cima de las Cumbres, Monterrey",
"Vista Hermosa, Monterrey",
"Residencial Dinastía, Monterrey",
"Bosques de Valle Alto, Monterrey",
"Vistancia, Monterrey",
"Cadereyta Jimenez Centro, Cadereyta Jiménez",
"Ciudad Cnop, Guadalupe",
"Los Faisanes, Guadalupe",
"Las Lajas, Monterrey",
"Santa Maria Pesquería, Pesquería",
"Centro Villa de Garcia (casco), García",
"Privadas del Sauce, General Escobedo",
"Apodaca",
"El Barrial, Santiago",
"Mirador, Monterrey",
"Contry, Monterrey",
"Rincón de Guadalupe, Guadalupe",
"Valle San Felipe, García",
"Independencia, Monterrey",
"Cadereyta Jiménez",
"Valle de las Palmas I, Apodaca",
"Ciudad Solidaridad, Monterrey",
"Buenos Aires, Monterrey",
"Country La Silla Sect 1, Guadalupe",
"San Jemo, Monterrey",
"Residencial el Encanto II, Monterrey",
"Valles de Guadalupe, Guadalupe",
"Huajuquito, Santiago",
"Residencial Casa Bella, San Nicolás de los Garza",
"Jardines de Andalucía, Guadalupe",
"Leones, Monterrey",
"Lomas de Santa Mónica I, Juárez",
"Península, García",
"Lomas Del Valle, San Pedro Garza García",
"Paseo de Cumbres, Monterrey",
"CROC, Monterrey",
"Lagos Del Bosque, Monterrey",
"Las Puentes Sect 9, San Nicolás de los Garza",
"Vista Real, San Pedro Garza García",
"San Nicolás de los Garza Centro, San Nicolás de los Garza",
"Riberas de Dos Ríos, Guadalupe",
"Churubusco, Monterrey",
"Hacienda las Margaritas I, Apodaca",
"Rincón de La Sierra, Guadalupe",
"Porto Cumbres, García",
"Cumbres del Sol, Monterrey",
"Country La Costa, Guadalupe",
"México 86, Guadalupe",
"Privada Residencial El Vergel, Monterrey",
"Monterrey Centro, Monterrey",
"Puerta de Hierro Cumbres, Monterrey",
"Reforma, Monterrey",
"Los Ébanos Norte, Apodaca",
"Cumbres Britania, García",
"Apodaca Centro, Apodaca",
"Bosques de las Cumbres, Monterrey",
"Valle Del Huajuco, Monterrey",
"Paseo de las Flores 1er Sector, Apodaca",
"Del Paseo Residencial, Monterrey",
"Las Lomas, García",
"Santa Engracia, San Pedro Garza García",
"Sierra Morena, Guadalupe",
"Del Norte, Monterrey",
"Lomas de La Paz, Apodaca",
"Privada de Santa Catarina, Santa Catarina",
"Country La Silla Sect 6, Guadalupe",
"Lomas Del Hípico, Monterrey",
"San Francisco, Santiago",
"La Loma, General Escobedo",
"Guadalupe",
"Jardines de La Boca, Santiago",
"Juárez, Juárez",
"Colinas de La Sierra Madre, San Pedro Garza García",
"Condado de Asturias, Santiago",
"Club de Golf La Herradura, Monterrey",
"Lomas Del Roble, San Nicolás de los Garza",
"Jardines de Escobedo II, General Escobedo",
"Tecnológico, Monterrey",
"Las Lomas, Juárez",
"La Purísima, Guadalupe",
"Las Brisas, Monterrey",
"Hacienda La Silla, Guadalupe",
"La Primavera 3er Sect, Monterrey",
"Las Hadas, General Escobedo",
"Real de San Jerónimo, Monterrey",
"Infonavit Topo Grande IV, General Escobedo",
"Ciudad Guadalupe Centro, Guadalupe",
"Ciudad CROC, Guadalupe",
"Ciudad Satélite, Monterrey",
"Villas de Lindavista, Monterrey",
"Residencial El Roble, San Nicolás de los Garza",
"Veredalta, San Pedro Garza García",
"Valle Alto, Monterrey",
"Fuentes de Santa Lucia, Apodaca",
"Arboledas de San Roque, Juárez",
"Colonial de San Jerónimo, Monterrey",
"Valle Sur, Juárez",
"Mitras Sur, Monterrey",
"Chepevera, Monterrey",
"Cumbres Elite Sector Villas, Monterrey",
"Las Misiones, Santiago",
"Privada Iltamarindo, Apodaca",
"Bello Amanecer Residencial, Guadalupe",
"Santa Lucia, General Escobedo",
"Lomas de Santa Catarina, Santa Catarina",
"Puerta de Anáhuac, General Escobedo",
"Colinas Del Rey, Guadalupe",
"Lagos del Vergel, Monterrey",
"Palo Blanco, San Pedro Garza García",
"Del Valle, San Pedro Garza García",
"Paseo Santa Rosa, Apodaca",
"General Escobedo",
"Roma, Monterrey",
"Los Prados Residencial, Apodaca",
"Lomas Del Paseo, Monterrey",
"Cumbres Andara, García",
"Portón de Valle Alto, Monterrey",
"La Escondida, Monterrey",
"Guadalupe Victoria, Guadalupe",
"20 de Noviembre, Guadalupe",
"Valle Del Virrey, Juárez",
"Villa Alegre, Monterrey",
"Felipe Carrillo Puerto, General Escobedo",
"Valle de Santa Engracia, San Pedro Garza García",
"Moderno Apodaca, Apodaca",
"Pedregal de San Agustín, General Escobedo",
"Gral. Escobedo Centro, General Escobedo",
"Fraccionamiento Campestre Sertoma, Monterrey",
"Balcones de Santo Domingo, San Nicolás de los Garza",
"San Jerónimo, Monterrey",
"Cumbres Mediterráneo, Monterrey",
"Nuevo Santa Maria, Guadalupe",
"Valles de Santiago, Santiago",
"Balcones Del Campestre, San Pedro Garza García",
"Las Privanzas Segundo, San Pedro Garza García",
"Hacienda de las Flores, Ciénega de Flores",
"Jardines Coloniales, San Pedro Garza García",
"San Pedro, Santiago",
"Hacienda de Juárez, Juárez",
"Las Estaciones, Monterrey",
"Residencial California, General Escobedo",
"Villa Universidad, San Nicolás de los Garza",
"Las Privanzas Primero, San Pedro Garza García",
"Cumbres de Santa Clara, Monterrey",
"Atongo de Allende, Allende",
"Mirasierra, San Pedro Garza García",
"Talleres, Monterrey",
"Bosques de La Huasteca, Santa Catarina",
"San Nicolás de los Garza",
"Diaz Ordaz, San Nicolás de los Garza",
"El Barro, Monterrey",
"Cumbres Madeira, Monterrey",
"Misión de San Miguel, Apodaca",
"Residencial Punta Esmeralda, Juárez",
"Paseo de las Mitras, Monterrey",
"Santoral, García",
"Valle de las Cumbres, Monterrey",
"Puerta de Hierro, Monterrey",
"Privada Residencial La Rioja, Monterrey",
"Loma Larga, Monterrey",
"Zona Valle Oriente, San Pedro Garza García",
"Balcones Del Norte 3er Sector, Apodaca",
"San Bernabe, Monterrey",
"Mitras Poniente, García",
"Cumbres Platino, Monterrey",
"Cumbres San Agustin, Monterrey",
"Las Margaritas, Santiago",
"Mitras Norte, Monterrey",
"Centro Sección, Allende",
"San Rafael, Guadalupe",
"Arroyo Seco, Monterrey",
"Capellanía Residencial, Apodaca",
"Mirador de La Silla, Guadalupe",
"Huasteca Del Valle, Santa Catarina",
"Mitras Poniente Sector Cedral, García",
"Valle de Huinalá, Apodaca",
"Provivienda Tepeyac, Santa Catarina",
"Contry Sol, Guadalupe",
"Villa Rosario, Santiago",
"Residencial Apodaca, Apodaca",
"Rincón de La Montaña, San Pedro Garza García",
"Las Lomas Sector Bosques, García",
"Colonial San Agustin, San Pedro Garza García",
"Canterías, Monterrey",
"Ciudad Cumbres, García",
"Los Olivos, General Escobedo",
"Vistalta 1er Sector, Monterrey",
"Privada Vista a la Sierra, Santa Catarina",
"Residencial San Agustin, San Pedro Garza García",
"Antigua Hacienda Santa Anita, Monterrey",
"Los Cavazos, Santiago",
"Treviño, Monterrey",
"Rincón de La Sierra, Monterrey",
"Industrias Del Vidrio, San Nicolás de los Garza",
"Vista Sol, Guadalupe",
"Jardín Español, Monterrey",
"Mitras Centro, Monterrey",
"Villazul, San Nicolás de los Garza",
"Zona Valle Poniente, San Pedro Garza García",
"Fresnos X, Apodaca",
"Bosques de Anáhuac, San Nicolás de los Garza",
"Cumbre Alta, Monterrey",
"Villas Del Roble, San Nicolás de los Garza",
"Anáhuac, San Nicolás de los Garza",
"Bosques Del Country A, Guadalupe",
"Real de Cumbres, Monterrey",
"San Isidro, San Nicolás de los Garza",
"Cerradas de Anáhuac Sector Premier, General Escobedo",
"Hacienda de Anáhuac, General Escobedo",
"Plaza Revolución, Monterrey",
"Residencial Cordillera, Santa Catarina",
"Las Puentes Sect 8, San Nicolás de los Garza",
"Soria, Monterrey",
"Del Valle Sect Oriente, San Pedro Garza García",
"Los Colorines, San Pedro Garza García",
"Privanzas 5 Sector, Monterrey",
"Paseo Del Prado, Juárez",
"Villas de Alcalá, Ciénega de Flores",
"Jardines de Santa Catarina, Santa Catarina",
"La Huasteca 1er Sect, Santa Catarina",
"San Jose Sur, Santiago",
"Valle Del Nogalar, San Nicolás de los Garza",
"Country La Silla Sect 4, Guadalupe",
"Misión de Anáhuac, General Escobedo",
"Privada Del Uro, Monterrey",
"Villa de Oriente, Juárez",
"Santa Cecilia, Apodaca",
"Valle de San Carlos, San Nicolás de los Garza",
"Jardines de La Silla, Juárez",
"Paseo Palmas I, Apodaca",
"Tacubaya, Guadalupe",
"Privadas de Santa Rosa, Apodaca",
"Las Puentes Sect 4, San Nicolás de los Garza",
"San Andres, Apodaca",
"Hacienda Santa Clara, Monterrey",
"Jardines de San Patricio, Apodaca",
"Riberas Del Country, Guadalupe",
"Cerradas de Anáhuac Residencial, General Escobedo",
"Industrial, Monterrey",
"Privadas de Anáhuac Sector Irlandés, General Escobedo",
"Jardines Del Paseo, Monterrey",
"Privada Residencial Villas Del Uro, Monterrey",
"Villas Del Mirador, Santa Catarina",
"Urbivilla Colonial, Monterrey",
"Privadas Purísima, Guadalupe",
"Valle de las Brisas, Monterrey",
"Paraíso, Guadalupe",
"Pedregal de La Huasteca, Santa Catarina",
"Jardines de Casa Blanca, San Nicolás de los Garza",
"San Pedro El Álamo, Santiago",
"Valle de San Angel Rincón Francés, San Pedro Garza García",
"La Esperanza, Juárez",
"Arturo Cavazos, Santiago",
"Country La Escondida, Guadalupe",
"Valle de San Miguel, Apodaca",
"Lolyta, Guadalupe",
"Country Sol Sect 1, Guadalupe",
"Valle del Salduero, Apodaca",
"Cumbres San Patricio, García",
"Celestino Gasca, General Escobedo",
"Satélite Acueducto, Monterrey",
"Dr. Coss, Dr. Coss",
"Las Callejas, Monterrey",
"Villas de San Jose, Juárez",
"Colonial La Sierra, San Pedro Garza García",
"Renacimiento, Monterrey",
"Piedra de Fierro, Santiago",
"Portales de Santiago, Santiago",
"Raul Caballero Escamilla, Santiago",
"Colinas Del Sur, Monterrey",
"La Amistad, Guadalupe",
"Villa Del Rio, Monterrey",
"El Mirador de La Huasteca, Santa Catarina",
"Gonzalitos, Monterrey",
"Las Jacarandas, Monterrey",
"San Jose Norte, Santiago",
"San Miguelito, Juárez",
"Santa Maria, San Nicolás de los Garza",
"Misión San Juan, García",
"La Puerta de La Huasteca, Santa Catarina",
"Residencial Chipinque, San Pedro Garza García",
"Paseo del Vergel, Monterrey",
"Punta La Boca, Santiago",
"La Lagrima, Monterrey",
"Mitras Poniente Ensenada, García",
"Valle de Bosquencinos, Monterrey",
"Real Hacienda de Huinalá, Apodaca",
"Hacienda las Palmas, Apodaca",
"La Montaña, García",
"Residencial Joyas de Huinalá, Apodaca",
"Florida, Monterrey",
"Los Cedros, Monterrey",
"Villa Santa Isabel, Monterrey",
"Residencial Florida, Monterrey",
"Balcones de Anáhuac Sect 1, San Nicolás de los Garza",
"Portal Del Fraile, General Escobedo",
"La Concordia, Santa Catarina",
"Los Azulejos, Monterrey",
"El Roble, San Nicolás de los Garza",
"Ignacio Zaragoza, Guadalupe",
"Torremolinos, Monterrey",
"Las Colinas, Monterrey",
"3 Caminos, Guadalupe",
"Sierra Ventana, Monterrey",
"Lindavista, Guadalupe",
"Agua Fría, Apodaca",
"Residencial los Angeles Sect 1, San Nicolás de los Garza",
"Villa Española, Guadalupe",
"Sabinitos Infonavit, Cadereyta Jiménez",
"Valle Azul, Apodaca",
"Valle de las Palmas IV, Apodaca",
"Villa las Fuentes, Monterrey",
"Alhambra, Monterrey",
"La Ermita, Santa Catarina",
"Jardines de San Agustin, San Pedro Garza García",
"La Estanzuela, Monterrey",
"Valle de las Grutas, García",
"San Pablo, Monterrey",
"Bosques Del Valle, San Pedro Garza García",
"Valle de Chapultepec, Guadalupe",
"Jardines de Lindavista, Guadalupe",
"Santa Catarina Centro, Santa Catarina",
"Urbivilla Del Rey, Monterrey",
"Las Puentes Sect 1, San Nicolás de los Garza",
"Las Puentes Sect 2, San Nicolás de los Garza",
"Privadas de Santa Catarina Sector Elite, Santa Catarina",
"Rinconada Colonial, Apodaca",
"Jardines de San Rafael, Guadalupe",
"Quintas las Sabinas, Juárez",
"Ébanos VII, Apodaca",
"Portal Cumbres, Monterrey",
"Real de Palmas, General Zuazua",
"Portal del Norte, General Zuazua",
"Los Amarantos, Apodaca",
"San Roque, Juárez",
"Alberos, Cadereyta Jiménez",
"Jardines de Villa Juárez, Juárez",
"Villas de La Herradura, Monterrey",
"Santa Bárbara, San Pedro Garza García",
"Bosques de La Pastora, Guadalupe",
"Jardín Cumbres, Monterrey",
"Valle de Lincoln, García",
"Jose Luis Lozano, Cadereyta Jiménez",
"Cosmópolis Metroplex, Apodaca",
"El Cercado Centro, Santiago",
"Lomas Del Campestre, San Pedro Garza García",
"Valle de San Angel, San Pedro Garza García",
"Libertad, Guadalupe",
"Los Pilares, Salinas Victoria",
"Villas de Oriente, San Nicolás de los Garza",
"Country Sur, Monterrey",
"Palmas Diamante, San Nicolás de los Garza",
"Los Olmos, San Pedro Garza García",
"Eduardo A Elizondo, Allende",
"Los Robles, Apodaca",
"Residencial Cumbres, Monterrey",
"Villa Murano, Monterrey",
"Solidaridad Barrio Del Centro, Monterrey",
"Lomas de Tampiquito, San Pedro Garza García",
"Coyoacan, Monterrey",
"Arboledas de Santo Domingo, San Nicolás de los Garza",
"Ignacio Ramirez, San Nicolás de los Garza",
"Rincón de San Francisco, San Pedro Garza García",
"Privalia Concordia, Apodaca",
"Los Pinos, Apodaca",
"Solidaridad Barrio Estrella, Monterrey",
"La Cantera, General Escobedo",
"El Uro Oriente, Monterrey",
"Puesta Del Sol, Guadalupe",
"Olinca, Santa Catarina",
"Valle de Zuazua, General Zuazua",
"Tampiquito, San Pedro Garza García",
"Los Cenizos, Santa Catarina",
"Rinconada, García",
"Juárez",
"La Ciudadela, Juárez",
"Alamedas de La Hacienda, Guadalupe",
"Privada Residencial Bosques Del Vergel, Monterrey",
"Los Reyes, Juárez",
"Centro de Desarrollo Comunitario CEDECO, San Nicolás de los Garza",
"Hacienda San Agustin, San Pedro Garza García",
"Nexxus XXI, General Escobedo",
"Las Cristalinas, Santiago",
"El Ranchito, Santiago",
"Laderas Del Mirador, Monterrey",
"Valle Dorado, San Nicolás de los Garza",
"San Pedro Garza García",
"Valle Del Country, Guadalupe",
"Las Alamedas, Montemorelos",
"Nuevo San Rafael (fomerrey 7), Guadalupe",
"Quinta Montecarlo, San Nicolás de los Garza",
"Renaceres Residencial, Apodaca",
"La Trinidad, Juárez",
"Renacimiento, General Escobedo",
"San Andres, Santiago",
"Rinconada San Juan, Juárez",
"Fuentes de Valle Sector 7 Colinas, San Pedro Garza García",
"San Francisco, San Pedro Garza García",
"Privadas de Anáhuac Sector Francés, General Escobedo",
"Lomas de Garcia, García",
"Privadas de las Villas, García",
"Colinas Del Rio, Juárez",
"Lomas Del Cercado, Santiago",
"Antigua, Monterrey",
"Las Jaras, Monterrey",
"Ciudad Cerralvo, Cerralvo",
"Colinas de San Juan, Juárez",
"Hacienda Real, Juárez",
"Residencial Escobedo, General Escobedo",
"Privadas Borneo, Apodaca",
"General Zaragoza",
"Fresnos I, Apodaca",
"Bosques de las Lomas, Santiago",
"Jerónimo Siller, San Pedro Garza García",
"Jardines Del Mezquital, San Nicolás de los Garza",
"Cerro de La Silla UC, Guadalupe",
"Valle de San Andres, Apodaca",
"Carmen Romano de Lopez Portillo (fomerrey 27), San Nicolás de los Garza",
"Barrio de La Industria, Monterrey",
"Benito Juárez",
"Palmares Residencial, Monterrey",
"Hacienda Del Valle, San Pedro Garza García",
"Pablo A de La Garza, Monterrey",
"Los Lirios, Apodaca",
"Valle Verde 2o Sect, Monterrey",
"Pinos IV, Apodaca",
"Balcones de San Miguel, Guadalupe",
"Puerta Del Sol, General Escobedo",
"El Sabino, Monterrey",
"Santa Cecilia, Monterrey",
"Privada San Miguel, Guadalupe",
"La Montaña, San Pedro Garza García",
"Solidaridad Barrio Santa Isabel, Monterrey",
"San Pedro, San Pedro Garza García",
"Lomas de Satélite, Monterrey",
"Rincón de Anáhuac, San Nicolás de los Garza",
"Las Alamedas, Linares",
"Residencial Nogalar, San Nicolás de los Garza",
"Las Villas, Guadalupe",
"Viejo Roble, San Nicolás de los Garza",
"Camino Real, Guadalupe",
"Linares Centro, Linares",
"Pedregal Cumbres, Monterrey",
"Nueva Esperanza 2, General Escobedo",
"Colinas de Liverpool, Monterrey",
"Misión Cumbres, Monterrey",
"Cumbres Del Valle, Monterrey",
"Lomas Del Poniente, Santa Catarina",
"Los Angeles Bosque Residencial, Monterrey",
"Riveras de San Nicolás, San Nicolás de los Garza",
"Las Puentes, San Nicolás de los Garza",
"Valle Torremolinos, Guadalupe",
"Bosques Del Roble, San Nicolás de los Garza",
"Privada Fundadores, Monterrey",
"Hacienda los Morales, San Nicolás de los Garza",
"Lomas Altas, Santa Catarina",
"Fidel Velázquez, Cadereyta Jiménez",
"Carmen",
"Acanto Residencial, Apodaca",
"Las Palmas, Apodaca",
"Valle Del Topo Chico, Monterrey",
"Ex-Hacienda San Francisco, Apodaca",
"Residencial San Nicolás, San Nicolás de los Garza",
"Jardines de Mirasierra, San Pedro Garza García",
"La Muralla, San Pedro Garza García",
"Privadas de Anáhuac Sector Mediterráneo, General Escobedo",
"Privadas de Anáhuac, General Escobedo",
"Urbivilla del Cedro, Monterrey",
"Prados de Santa Catarina, Santa Catarina",
"Jardines de San Andres Sector 2, Apodaca",
"Industrias Del Vidrio Oriente, San Nicolás de los Garza",
"Urbivilla Bonita, Monterrey",
"Balcones Del Carmen, Monterrey",
"Cerradas del Parque, Apodaca",
"Cortijo Del Rio, Monterrey",
"Nueva Lindavista, Guadalupe",
"Balcones de Santa Rosa, Apodaca",
"Cumbres Provenza Privada Terra, García",
"Las Sombrillas, Santa Catarina",
"Terminal, Monterrey",
"Campestre Bugambilias, Monterrey",
"Residencial Cuauhtémoc, Santa Catarina",
"Quintas de Anáhuac, General Escobedo",
"18 de Octubre, General Escobedo",
"Niño Artillero, Monterrey",
"Miravista, General Escobedo",
"Bosques de San Miguel, Apodaca",
"Solidaridad Barrio San Luis, Monterrey",
"Rincón de La Villa, Santa Catarina",
"Monticello, García",
"Lomas Quetzales, García",
"Lomas de Cumbres, Monterrey",
"Nexxus Residencial Sector Platino, General Escobedo",
"Avita Anahuac, San Nicolás de los Garza",
"Escamilla, Guadalupe",
"Paraje Anahuac, General Escobedo",
"Residencial Santa Fe, Guadalupe",
"Privada San Fernando, Guadalupe",
"El Refugio, Monterrey",
"Valle de Guadalupe, Guadalupe",
"Las Puentes Sect 3, San Nicolás de los Garza",
"Gral. Zuazua, General Zuazua",
"Jardines Nueva Lindavista, Guadalupe",
"Salinas Victoria, Salinas Victoria",
"Casa Blanca, San Nicolás de los Garza",
"Las Dalias, Guadalupe",
"Rincón Del Valle, Monterrey",
"Zambrano, Montemorelos",
"Valle San Rafael, Guadalupe",
"Unidad Laboral, San Nicolás de los Garza",
"Deportivo Obispado, Monterrey",
"Villa de los Pinos, Monterrey",
"Los Almendros, Monterrey",
"Joyas de Anáhuac, General Escobedo",
"Riberas Del Rio Sector I, Guadalupe",
"Collados de Guadalupe 2do Sector, Guadalupe",
"Vivienda Digna, Apodaca",
"Villas de Anáhuac, General Escobedo",
"Prados de La Sierra, San Pedro Garza García",
"Balcones de Santa Catarina (fomerrey 134), Santa Catarina",
"Tréboles, Apodaca",
"Misión San Jose, Apodaca",
"Exhacienda El Rosario, Juárez",
"Colinas Del Valle, Monterrey",
"Las Palmas, Cadereyta Jiménez",
"Miguel Aleman, San Nicolás de los Garza",
"La Hacienda, Monterrey",
"Villa de San Miguel, Guadalupe",
"Las Espigas 2do Sector, Cadereyta Jiménez",
"Anáhuac, Anáhuac",
"Guadalupe, Monterrey",
"Cerro de La Silla, Monterrey",
"Valle de Los Nogales 1ra Etapa, Apodaca",
"Praderas de Guadalupe, Guadalupe",
"Ondara, Santa Catarina",
"Balcones Del Norte 1er Sector, General Escobedo",
"Quinta Colonial Apodaca, Apodaca",
"Jacarandas, Apodaca",
"Los Olivos, Apodaca",
"Cumbres de Santa María, García",
"Monte Verde, Juárez",
"Riberas de Capellania, García",
"Las Puentes Sect 6, San Nicolás de los Garza",
"Ventura de Asís, Apodaca",
"Los Candiles, Apodaca",
"Ciudad Azteca, Guadalupe",
"La Alianza, Monterrey",
"Satélite Miradores, Monterrey",
"Santa Rosa, Apodaca",
"Hacienda las Fuentes, San Nicolás de los Garza",
"Solidaridad Barrio Del Prado, Monterrey",
"La Cantera Privada Residencial, General Escobedo",
"Las Villas, San Nicolás de los Garza",
"Country San Juanito, Monterrey",
"Valles de La Silla, Guadalupe",
"Carrizalejo, San Pedro Garza García",
"Ancira, Monterrey",
"Vista Montaña, San Pedro Garza García",
"Hacienda Del Carmen, Apodaca",
"La Hacienda, Guadalupe",
"Arboledas Nueva Lindavista, Guadalupe",
"Valle de La Esperanza, Monterrey",
"Misión Santa Catarina, Santa Catarina",
"Residencial Bosquencinos, Monterrey",
"Los Parques, García",
"Progreso, Monterrey",
"Valle Sol, San Nicolás de los Garza",
"Torres de Garcia, García",
"Colinas de Anahuac, San Nicolás de los Garza",
"Collados de Guadalupe, Guadalupe",
"La Joya, Santa Catarina",
"Los Encinos, Allende",
"Rincón Colonial, San Pedro Garza García",
"San Jose, Monterrey",
"Cumbres de Santa Catarina, Santa Catarina",
"Torremolinos La Fe, Guadalupe",
"San Agustin, San Pedro Garza García",
"Hacienda de Santo Domingo, San Nicolás de los Garza",
"Valle de Chipinque, San Pedro Garza García",
"Lázaro Garza Ayala, San Pedro Garza García",
"Paseo Palmas II, Apodaca",
"Roble San Nicolás, San Nicolás de los Garza",
"Praderas de La Enramada, Apodaca",
"Los Tres Nogales, Apodaca",
"Las Espigas, Cadereyta Jiménez",
"Barrio Puerta del Sol, Monterrey",
"San Pedro, Monterrey",
"Colinas de Valle Verde, Monterrey",
"Visión de La Huasteca, Santa Catarina",
"Santa Catalina, Santa Catarina",
"Misión Del Valle, San Pedro Garza García",
"Misión Santa Fe, Guadalupe",
"Las Torres, Monterrey",
"San Juan Bautista, García",
"Santa Catarina",
"Parque Industrial II, General Escobedo",
"Pedregal, Monterrey",
"Mirador de Santa Catarina, Santa Catarina",
"Privada la Castaña, Apodaca",
"Paseo de la Loma, Apodaca",
"Pio X, Monterrey",
"Los Viñedos, Santa Catarina",
"Los Vitrales, Apodaca",
"Molino Del Rey, Guadalupe",
"Loma Linda, Monterrey",
"Fidel Velázquez Sect 1, San Nicolás de los Garza",
"Santa Maria, Cadereyta Jiménez",
"Residencial Aztlán, Monterrey",
"Potrero Anáhuac, San Nicolás de los Garza",
"Hacienda los Cantu, General Escobedo",
"Las Provincias, Apodaca",
"Cumbres Renacimiento, Monterrey",
"Santa Lucia, Apodaca",
"Topo Chico, Monterrey",
"Privada Cumbres Diamante, Monterrey",
"Jardines de San Jorge, Apodaca",
"Madeira Residencial, Apodaca",
"Real de San Andres, Apodaca",
"Altaria Residencial, Apodaca",
"Misión Fundadores, Apodaca",
"San Francisco, Apodaca",
"Bosque de Agua, Apodaca",
"Prados de Santa Rosa, Apodaca",
"Privadas Del Parque, Apodaca",
"Bosque Del Sol, Apodaca",
"Nueva las Puentes I, Apodaca",
"Arboledas Del Mezquital, Apodaca",
"La Hacienda, Apodaca",
"Portal Anáhuac, Apodaca",
"Villas de Santa Rosa, Apodaca",
"Amberes Residencial, Apodaca",
"Fraccionamiento San Andres, Apodaca",
"Crystal Lagoons, Apodaca",
"Privada Pedregal Del Valle, Apodaca",
"Real de Apodaca, Apodaca",
"Paraje Santa Rosa, Apodaca",
"San Miguel Golondrinas III, Apodaca",
"Misión San Patricio, Apodaca",
"Valle de Apodaca I, Apodaca",
"Antigua Santa Rosa, Apodaca",
"Hacienda los Nogales, Apodaca",
"Jardines de Huinalá, Apodaca",
"Monte Alban II, Apodaca",
"Valle de Los Nogales 2da Etapa, Apodaca",
"Ventura de Santa Rosa, Apodaca",
"Hacienda Santa Fe, Apodaca",
"Privada San Miguelito, Apodaca",
"Álamos Del Parque, Apodaca",
"Los Encinos Residencial, Apodaca",
"Paseo de las Fuentes, Apodaca",
"Privadas Rinconada, Apodaca",
"Huinalá, Apodaca",
"San Ignacio, Apodaca",
"Reforma I, Apodaca",
"Arboledas de Santa Rosa, Apodaca",
"Misión Real, Apodaca",
"Villas Premier, Apodaca",
"Metroplex 1, Apodaca",
"Nuevo Mezquital, Apodaca",
"Nuevo Amanecer 1, Apodaca",
"Fresnos IV, Apodaca",
"Valle de las Palmas II, Apodaca",
"Bosque Boreal, Apodaca",
"Rincón de San Miguel, Apodaca",
"San Miguel Golondrinas I, Apodaca",
"Los Encinos, Apodaca",
"Hacienda los Pinos, Apodaca",
"Magnolias, Apodaca",
"La Enramada, Apodaca",
"Recova Residencial, Apodaca",
"Santa Fe, Apodaca",
"Misión San Pablo, Apodaca",
"San Isidro I, Apodaca",
"Joyas Del Pedregal, Apodaca",
"Golondrinas, Apodaca",
"Exhacienda Santa Rosa, Apodaca",
"Alianza, Apodaca",
"Bosques de Huinalá, Apodaca",
"Deportivo Huinalá, Apodaca",
"Benito Juárez, Apodaca",
"San Benito Del Lago, Apodaca",
"Bosque Real II, Apodaca",
"Parque Industrial Milimex, Apodaca",
"El Milagro, Apodaca",
"Misión de Huinalá, Apodaca",
"Los Fresnos Norte, Apodaca",
"MIRASOL, Apodaca",
"Privada Premier, Apodaca",
"Rincón de los Cristales, Apodaca",
"Hacienda Del Mezquital, Apodaca",
"Burócratas Municipales, Apodaca",
"Insurgentes, Apodaca",
"Cerradas de Santa Rosa, Apodaca",
"Cerrada la Toscana, Apodaca",
"Milenium Residencial, Apodaca",
"Deportivo Huinalá Mundialista, Apodaca",
"Metroplex 2, Apodaca",
"Valle de las Bugambilias, Apodaca",
"Paseo de los Nogales, Apodaca",
"Privalia Huinalá, Apodaca",
"Villas de las Puentes, Apodaca",
"Ébanos XI, Apodaca",
"Ébanos IX, Apodaca",
"San Miguel, Apodaca",
"Privadas del Rey, Apodaca",
"Hacienda El Campanario, Apodaca",
"Pedregal de Apodaca, Apodaca",
"Nova Apodaca, Apodaca",
"Fresnos VIII, Apodaca",
"Santa Mónica, Apodaca",
"Los Ébanos, Apodaca",
"Paseo Palmas IV, Apodaca",
"Quinta Real, Apodaca",
"Noria Sur, Apodaca",
"Hacienda los Yucas, Apodaca",
"Monterrey, Apodaca",
"Álamos, Apodaca",
"Pueblo Nuevo 1, Apodaca",
"Los Altos, Apodaca",
"Las Estancias, Apodaca",
"Quinta Colonial  Apodaca 2do Sector, Apodaca",
"Colinas de San Miguel, Apodaca",
"Ébanos III, Apodaca",
"Loma de La Paz, Apodaca",
"Villas Del Huinalá, Apodaca",
"Villa de Huinalá II, Apodaca",
"Colonial de Huinalá, Apodaca",
"Campestre Huinalá, Apodaca",
"Hacienda las Margaritas IV, Apodaca",
"El Molino, Apodaca",
"Mujeres Ilustres, Apodaca",
"Montealban, Apodaca",
"Artemio Treviño, Apodaca",
"Ébanos V, Apodaca",
"Valle Del Mezquital, Apodaca",
"Ébanos IV, Apodaca",
"Enramada VII, Apodaca",
"Jardines de Apodaca, Apodaca",
"Futuro Apodaca, Apodaca",
"Praderas I, Apodaca",
"Las Américas, Apodaca",
"Palmas 1 Sector, Apodaca",
"Misión Del Valle, Guadalupe",
"San Antonio, Guadalupe",
"Lomas de San Miguel, Guadalupe",
"Santa Maria, Guadalupe",
"La Victoria, Guadalupe",
"Residencial Azteca, Guadalupe",
"Almaguer, Guadalupe",
"Residencial Guadalupe, Guadalupe",
"Insurgentes, Guadalupe",
"Riveras de Nueva Lindavista, Guadalupe",
"Arboledas de San Miguel, Guadalupe",
"Los Sauces, Guadalupe",
"La Playa, Guadalupe",
"División Del Norte, Guadalupe",
"Portales de La Silla, Guadalupe",
"Cerro de La Silla, Guadalupe",
"La Comedia, Guadalupe",
"Rafael Ramirez, Guadalupe",
"Residencial las Quintas, Guadalupe",
"Crispín Treviño, Guadalupe",
"Country La Silla Sect 5, Guadalupe",
"Privada San Carlos, Guadalupe",
"Country La Silla Sect 8, Guadalupe",
"Marte, Guadalupe",
"La Luz, Guadalupe",
"Torres de San Miguel, Guadalupe",
"15 de Mayo, Guadalupe",
"Residencial Cerro de La Silla, Guadalupe",
"Vivienda Popular, Guadalupe",
"Cañón de La Silla, Guadalupe",
"Guadalupe Chavez, Guadalupe",
"Galerías Del Camino Real 2o Sector, Guadalupe",
"Gelerias Del Camino Real, Guadalupe",
"Libertadores II, Guadalupe",
"Canteras, Guadalupe",
"Cerradas de Lindavista, Guadalupe",
"Las Plazas 1, Guadalupe",
"Jardines de San Miguel, Guadalupe",
"Jardines La Pastora, Guadalupe",
"Valle de San Roque Infonavit, Guadalupe",
"Industrial La Silla, Guadalupe",
"Rafael Ramirez Sector II, Guadalupe",
"Misión Santa Cruz, Guadalupe",
"Paseo San Miguel, Guadalupe",
"Zertuche 1er Sect, Guadalupe",
"Valle de Lindavista, Guadalupe",
"Valle Hermoso Sect 1, Guadalupe",
"Evolución, Guadalupe",
"Xochimilco, Guadalupe",
"Santa Isabel, Guadalupe",
"Valle La Silla, Guadalupe",
"31 de Diciembre, Guadalupe",
"13 de Mayo, Guadalupe",
"Talaberna, Guadalupe",
"Alfonso Martinez Dominguez, Guadalupe",
"Misión de Guadalupe, Guadalupe",
"Roble Santa Maria, Guadalupe",
"Rincón de La Primavera Sect 4, Guadalupe",
"Bugambilias de La Sierra, Guadalupe",
"Veteranos de La Revolución, Guadalupe",
"La Herradura, Guadalupe",
"Praderas de La Silla, Guadalupe",
"Ribera de Lindavista, Guadalupe",
"Pedregal de Lindavista, Guadalupe",
"Los Olivos, Guadalupe",
"Tierra Propia Sect 1, Guadalupe",
"Privadas Del Rey, Guadalupe",
"Santa Cruz, Guadalupe",
"Lomas de San Roque, Guadalupe",
"Adolfo Prieto Sect 1, Guadalupe",
"México Nuevo, Guadalupe",
"Valle de los Encinos, Guadalupe",
"Nuevo San Miguel, Guadalupe",
"Valle de San Antonio, Guadalupe",
"Fuentes de San Miguel, Guadalupe",
"El Peñón, Guadalupe",
"Esmeralda, Guadalupe",
"Bosques Del Sol, Guadalupe",
"Bosques Del Country B, Guadalupe",
"Tamaulipas, Guadalupe",
"Santa Clara, Guadalupe",
"La Quinta, Guadalupe",
"Guadalupe La Silla, Guadalupe",
"Cañada Blanca, Guadalupe",
"Valle Soleado, Guadalupe",
"La Trinidad, Guadalupe",
"Villa San Miguel, Guadalupe",
"Azteca Sect 5, Guadalupe",
"Rincón de los Sabinos, Guadalupe",
"Los Encinos, Guadalupe",
"Privadas de Lindavista, Guadalupe",
"10 de Mayo, Guadalupe",
"Jose Luis Mora, Guadalupe",
"Rancho Viejo Sect 1, Guadalupe",
"Riveras de La Silla (fomerrey 31), Guadalupe",
"Fuentes de Guadalupe, Guadalupe",
"21 de Enero, Guadalupe",
"Hacienda San Miguel, Guadalupe",
"Jardines Del Rio, Guadalupe",
"Cortijo La Silla, Guadalupe",
"Las Colinas, Guadalupe",
"Real de Minas, Guadalupe",
"La Fuente, Guadalupe",
"Coloniales San Miguel Sect 1, Guadalupe",
"Pedregal de Guadalupe, Guadalupe",
"Real de San Miguel Sector I, Guadalupe",
"Rincón de La Hacienda, Guadalupe",
"Los Lermas, Guadalupe",
"Raul Caballero, Guadalupe",
"Nueva Aurora, Guadalupe",
"Acueducto Guadalupe, Guadalupe",
"Los Independientes, Guadalupe",
"Rincón de La Azteca, Guadalupe",
"Country Club, Guadalupe",
"Country La Silla Sect 2, Guadalupe",
"Santa Margarita, Guadalupe",
"Misión de La Silla, Guadalupe",
"Real de San Miguel Sector 4, Guadalupe",
"Niños Héroes, Guadalupe",
"3 Caminos Norte, Guadalupe",
"Nueva Exposición, Guadalupe",
"Residencial Minerva, Guadalupe",
"Emiliano Zapata (fomerrey 18), Guadalupe",
"La Joyita, Guadalupe",
"Solidaridad Barrio San Carlos, Monterrey",
"El Encino, Monterrey",
"Condocasas Cumbres, Monterrey",
"Las Plazas, Monterrey",
"Jardines Altavista, Monterrey",
"Pedro Lozano, Monterrey",
"Hacienda San Jerónimo, Monterrey",
"Colinas de San Gerardo, Monterrey",
"Nuevas Colonias, Monterrey",
"Real de Valle Alto, Monterrey",
"Lomas de Montecristo, Monterrey",
"El Palmar, Monterrey",
"Sarabia, Monterrey",
"Lomas, Monterrey",
"Cumbres Providencia, Monterrey",
"Bernardo Reyes, Monterrey",
"Colonial Cumbres, Monterrey",
"Valle Morelos, Monterrey",
"Prados de La Silla, Monterrey",
"Mitras Poniente, Monterrey",
"Cumbres Quinta Real, Monterrey",
"Hacienda San Francisco, Monterrey",
"Altamira, Monterrey",
"Ancon Del Huajuco, Monterrey",
"La Primavera 1er Sect, Monterrey",
"Lomas de Valle Alto, Monterrey",
"15 de Marzo, Monterrey",
"Valle Del Mirador, Monterrey",
"Industrial Lincoln, Monterrey",
"Residencial de la Sierra, Monterrey",
"Bella Vista, Monterrey",
"Villas de La Hacienda, Monterrey",
"Nuevo Repueblo, Monterrey",
"Contry los Nogales, Monterrey",
"El Rosario, Monterrey",
"Cañada Del Sur, Monterrey",
"Colinas de las Cumbres, Monterrey",
"El Mirador de las Mitras, Monterrey",
"Encinos, Monterrey",
"Villas de San Bernabe, Monterrey",
"Fontanares, Monterrey",
"Jardines Moderna, Monterrey",
"Rene Alvarez, Monterrey",
"Las Canteras, Monterrey",
"Fortín Del Huajuco, Monterrey",
"Villas Canterías, Monterrey",
"Maria Luisa, Monterrey",
"Los Encinos, Monterrey",
"Privada Santa Clara, Monterrey",
"Country Lux, Monterrey",
"Solidaridad Barrio Del Parque, Monterrey",
"Jardín de las Torres, Monterrey",
"Del Carmen, Monterrey",
"Mariano Escobedo, Monterrey",
"Solidaridad Barrio Moderna, Monterrey",
"Rincón de Santa Maria, Monterrey",
"Miravalle, Monterrey",
"Villa Dorada, Monterrey",
"Adolfo Ruiz Cortines, Monterrey",
"Valle de Infonavit, Monterrey",
"Lomas de Anáhuac, Monterrey",
"Moderna, Monterrey",
"Residencial Abraham Lincoln, Monterrey",
"Villa Florida, Monterrey",
"Satélite Acueducto Sur, Monterrey",
"San Jemo 3o, Monterrey",
"Obispado, Monterrey",
"Valle de Santa Lucia, Monterrey",
"Valle de las Mitras, Monterrey",
"Garza Nieto, Monterrey",
"Fomerrey 1, Monterrey",
"Roma Sur, Monterrey",
"Unidad Modelo, Monterrey",
"Country Naranjo, Monterrey",
"Villa las Palmas, San Pedro Garza García",
"Barranca Del Pedregal, San Pedro Garza García",
"Real de San Agustin, San Pedro Garza García",
"Lomas de San Angel, San Pedro Garza García",
"Valle Del Seminario, San Pedro Garza García",
"Colonial de la Sierra, San Pedro Garza García",
"Villa Del Valle, San Pedro Garza García",
"San Pedro Garza Garcia Centro, San Pedro Garza García",
"La Finca, San Pedro Garza García",
"Del Valle Sect Norte, San Pedro Garza García",
"San Agustin Campestre, San Pedro Garza García",
"Jardines Del Valle, San Pedro Garza García",
"Mesa de La Corona, San Pedro Garza García",
"Bosques de San Angel Sector Palmillas, San Pedro Garza García",
"Valle de San Angel Sect Mexicano, San Pedro Garza García",
"Valle de San Angel Sect Español, San Pedro Garza García",
"Real Del Valle, San Pedro Garza García",
"Villas de Santa Engracia, San Pedro Garza García",
"Balcones Del Valle, San Pedro Garza García",
"Del Valle Sect Fátima, San Pedro Garza García",
"Residencial Sierra Del Valle, San Pedro Garza García",
"Jesús M Garza, San Pedro Garza García",
"Privada Callejones, San Pedro Garza García",
"Pedregal Del Valle, San Pedro Garza García",
"El Obispo, San Pedro Garza García",
"Capistrano, San Pedro Garza García",
"Antigua Hacienda San Agustin, San Pedro Garza García",
"Los Sauces, San Pedro Garza García",
"Valle de Vasconcelos, San Pedro Garza García",
"Lomas de San Agustin, San Pedro Garza García",
"Olinalá, San Pedro Garza García",
"Mirador Del Campestre, San Pedro Garza García",
"Privada Fundadores, San Pedro Garza García",
"Jardines de Campestre, San Pedro Garza García",
"Las Sendas, San Pedro Garza García",
"Colina de San Angel, San Pedro Garza García",
"Ampliación Canteras, San Pedro Garza García",
"Valle de San Agustin, San Pedro Garza García",
"Valle de San Angel Sect Jardines, San Pedro Garza García",
"Sierra de Anáhuac, San Pedro Garza García",
"Valle Del Mirador, San Pedro Garza García",
"Zona Loma Larga Oriente, San Pedro Garza García",
"Olímpico, San Pedro Garza García",
"San Angel, San Pedro Garza García",
"Villas de Terrasol, San Pedro Garza García",
"Lomas Del Obispo, San Pedro Garza García",
"Ex - Hacienda San Agustin, San Pedro Garza García",
"Privada La Huasteca, Santa Catarina",
"Prados Del Rey, Santa Catarina",
"Privada Acueducto, Santa Catarina",
"Cantizal, Santa Catarina",
"El Frutal, Santa Catarina",
"Las Fincas, Santa Catarina",
"Ventanas de La Huasteca, Santa Catarina",
"Rincón de las Mitras, Santa Catarina",
"La Puerta, Santa Catarina",
"Industrias del Poniente, Santa Catarina",
"Bosques de Santa Catarina, Santa Catarina",
"Zimix Norte, Santa Catarina",
"Huasteca Real, Santa Catarina",
"La Fama 1, Santa Catarina",
"Infonavit La Huasteca, Santa Catarina",
"Mártires de Cananea, Santa Catarina",
"Aurora, Santa Catarina",
"Valle de La Sierra, Santa Catarina",
"Prados de San Jorge, Santa Catarina",
"Privadas de La Montaña, Santa Catarina",
"Residencial de Santa Catarina, Santa Catarina",
"Adolfo Lopez Mateos, Santa Catarina",
"Bosques Del Poniente, Santa Catarina",
"El Aguacatal, Santa Catarina",
"Industrial Unidad Nacional, Santa Catarina",
"Fama IV, Santa Catarina",
"El Escorial, Santa Catarina",
"Rincón de las Palmas, Santa Catarina",
"El Castillo, Santa Catarina",
"Loma Alta, Santa Catarina",
"Santa Catarina Infonavit, Santa Catarina",
"Real de Santa Catarina 2do Sector, Santa Catarina",
"Industrial Santa Catarina, Santa Catarina",
"Villas del Poniente Las Granadas, Santa Catarina",
"Arboledas de las Mitras, Santa Catarina",
"Tepeyac, Santa Catarina",
"Cordilleras Del Virrey, Santa Catarina",
"Prados Del Sol, Santa Catarina",
"Desarrollo Industrial Monterrey, Santa Catarina",
"Del Poniente, Santa Catarina",
"Jardines de Anáhuac Sect 1, San Nicolás de los Garza",
"Villas de Casa Blanca, San Nicolás de los Garza",
"Torres de Santo Domingo, San Nicolás de los Garza",
"Hacienda los Morales Sect 2, San Nicolás de los Garza",
"Real Anáhuac, San Nicolás de los Garza",
"Parque Anáhuac, San Nicolás de los Garza",
"Jardín de las Puentes, San Nicolás de los Garza",
"Santo Domingo, San Nicolás de los Garza",
"Villa Esperanza, San Nicolás de los Garza",
"Margarita Rodriguez Salazar CFE, San Nicolás de los Garza",
"Las Puentes Sect 5, San Nicolás de los Garza",
"Bosques de Lindavista, San Nicolás de los Garza",
"Los Morales, San Nicolás de los Garza",
"Los Nogales, San Nicolás de los Garza",
"Villas de Anáhuac, San Nicolás de los Garza",
"Francisco Villa, San Nicolás de los Garza",
"El Refugio Sect 1, San Nicolás de los Garza",
"Fresnos Del Lago, San Nicolás de los Garza",
"Las Puentes Sect 14, San Nicolás de los Garza",
"Residencial Periférico, San Nicolás de los Garza",
"Residencial Anáhuac, San Nicolás de los Garza",
"La Estancia, San Nicolás de los Garza",
"Jardines de Santo Domingo, San Nicolás de los Garza",
"Hacienda los Morales Sect 3, San Nicolás de los Garza",
"Industrias Del Vidrio Sect 2, San Nicolás de los Garza",
"Villas Santo Domingo, San Nicolás de los Garza",
"Los Mezquites, San Nicolás de los Garza",
"Valle de Anáhuac, San Nicolás de los Garza",
"Villa Luis, San Nicolás de los Garza",
"Portal Del Roble, San Nicolás de los Garza",
"Héroes de México, San Nicolás de los Garza",
"Rincón de los Ángeles, San Nicolás de los Garza",
"Costa Del Sol, San Nicolás de los Garza",
"Del Lago Sect 2, San Nicolás de los Garza",
"Praderas de Santo Domingo, San Nicolás de los Garza",
"Getsemani, San Nicolás de los Garza",
"La Talaverna, San Nicolás de los Garza",
"Las Puentes Sect 10, San Nicolás de los Garza",
"Villas San Cristóbal, San Nicolás de los Garza",
"Miraflores Sect 1, San Nicolás de los Garza",
"Del Vidrio, San Nicolás de los Garza",
"Las Alamedas, San Nicolás de los Garza",
"Los Angeles Infonavit Sect 3, San Nicolás de los Garza",
"El Fundador Diaz de Berlanga, San Nicolás de los Garza",
"Paseo de los Andes, San Nicolás de los Garza",
"Valle de las Flores, San Nicolás de los Garza",
"Hacienda El Roble, San Nicolás de los Garza",
"Pedregal de Santo Domingo, San Nicolás de los Garza",
"Colonial las Puentes, San Nicolás de los Garza",
"Tacuba, San Nicolás de los Garza",
"Francisco Garza Sada, San Nicolás de los Garza",
"Residencial las Puentes Sect 1, San Nicolás de los Garza",
"Nueva las Puentes II, San Nicolás de los Garza",
"Paseo de San Nicolás, San Nicolás de los Garza",
"Las Palmas, San Nicolás de los Garza",
"Residencial Nova, San Nicolás de los Garza",
"Prados de Santo Domingo, San Nicolás de los Garza",
"Jardines de San Nicolás, San Nicolás de los Garza",
"Arboledas Del Mezquital, San Nicolás de los Garza",
"Los Naranjos Sect 4, San Nicolás de los Garza",
"Bosques de Lindavista Sector Diamante, San Nicolás de los Garza",
"Residencial los Angeles Sect 2, San Nicolás de los Garza",
"San Cristóbal, San Nicolás de los Garza",
"Los Angeles Infonavit Sect 4, San Nicolás de los Garza",
"Roble Norte, San Nicolás de los Garza",
"Ancestra, San Nicolás de los Garza",
"Parque La Talaverna, San Nicolás de los Garza",
"El Centenario 2, San Nicolás de los Garza",
"Hacienda los Angeles, San Nicolás de los Garza",
"Misión de Casa Blanca 1er Sector, San Nicolás de los Garza",
"Bosques Del Nogalar, San Nicolás de los Garza",
"Constituyentes de Queretaro Sect 4, San Nicolás de los Garza",
"Nicolás Bravo Sect 1, San Nicolás de los Garza",
"Paseo de los Angeles, San Nicolás de los Garza",
"Vicente Guerrero (fomerrey 46), San Nicolás de los Garza",
"Nogalar, San Nicolás de los Garza",
"Laureles, San Nicolás de los Garza",
"Constituyentes de Queretaro Sect 1, San Nicolás de los Garza",
"Villa Luz, San Nicolás de los Garza",
"La Gloria, San Nicolás de los Garza",
"Industrial los Parques, San Nicolás de los Garza",
"Villas Del Poniente, García",
"Arco Vial, García",
"Cumbres Toscana, García",
"Real de Villas de Garcia, García",
"Grutas de Villa de Garcia, García",
"San Jose, García",
"Ciudad Industrial Mitras, García",
"Mirador, García",
"Lomas del Sur, García",
"Colinas Del Rio, García",
"San José Sector Aves, García",
"Mirador de Garcia, García",
"Las Villas, García",
"Atera Residencial, García",
"Mitras Poniente Ajusco, García",
"Popular Jose Páez Garcia, García",
"Cumbres la Rioja, García",
"Mitras Poniente Sector Jordan, García",
"El Cielo, García",
"Fomorrey Sobrevilla, García",
"Mitras Poniente Sector Salvatierra, García",
"Lincoln Poniente, García",
"Ayuccá, García",
"Alfonzo Martinez Dominguez, García",
"Cumbres Provenza Cerrada Lux, García",
"Mitras Poniente Sector Guadalcazar, García",
"Aura Residencial, García",
"Valle de San José 2do Sector, García",
"Valle de Lincoln San Agustín, García",
"La Gruta, García",
"Campestre Santa Clara, Santiago",
"Pedregal de Santiago , Santiago",
"La Boca, Santiago",
"Jardines de Santiago, Santiago",
"Los Pescadores, Santiago",
"Santa Tais, Santiago",
"15 de Mayo, Santiago",
"Cieneguilla, Santiago",
"Del Maestro, Santiago",
"Laguna de Sanchez, Santiago",
"Viento Libre, Santiago",
"Cola de Caballo, Santiago",
"Villa de Santiago, Santiago",
"Los Fierros, Santiago",
"Melchor Ocampo, Santiago",
"Potrero de Serna, Santiago",
"Las Hadas, Santiago",
"Nuevo Escobedo, General Escobedo",
"Nexxus Residencial Sector Dorado, General Escobedo",
"Ébanos y Nueva Esperanza, General Escobedo",
"Villas Mirasur, General Escobedo",
"Rio Pesquería Nuevas Puentes, General Escobedo",
"San Genaro II, General Escobedo",
"Paseo Real, General Escobedo",
"Escobedo, General Escobedo",
"Nueva Castilla, General Escobedo",
"Lomas de San Genaro, General Escobedo",
"Puerta Del Norte, General Escobedo",
"Hacienda Escobedo, General Escobedo",
"Pedregal Del Topo Chico, General Escobedo",
"Arcos Del Sol, General Escobedo",
"Parque Residencial I, General Escobedo",
"Exhacienda El Canada, General Escobedo",
"Valle de los Girasoles, General Escobedo",
"Fernando Amilpa, General Escobedo",
"Ciudad San Marcos, General Escobedo",
"Colinas Del Topo Chico (Fomerrey 49), General Escobedo",
"Hacienda Del Vergel, General Escobedo",
"Los Girasoles II, General Escobedo",
"Las Encinas, General Escobedo",
"Provileon, General Escobedo",
"Privada Del Angel, General Escobedo",
"Las Malvinas, General Escobedo",
"Nexxus Residencial Sector Rubí, General Escobedo",
"San Miguel, General Escobedo",
"Jardines Del Canada, General Escobedo",
"Rincón de Las Encinas, General Escobedo",
"Fuentes de Escobedo, General Escobedo",
"Nexxus Residencial Sector Diamante, General Escobedo",
"Fomerrey La Unidad, General Escobedo",
"Monte Real V, General Escobedo",
"California Fraccionamiento Primer Sector, General Escobedo",
"Praderas de los Girasoles, General Escobedo",
"Arboledas, General Escobedo",
"Balcones de Anáhuac I, General Escobedo",
"Monte Real, General Escobedo",
"Villas de San Francisco, General Escobedo",
"San Genaro, General Escobedo",
"Roble Nuevo, General Escobedo",
"La Concordia, General Escobedo",
"Los Girasoles, General Escobedo",
"La Unidad Sectores 1 y 2, General Escobedo",
"Fomerrey 9, General Escobedo",
"Villas de Anáhuac Sector Alpes, General Escobedo",
"Los Vergeles, General Escobedo",
"Villa Alta, General Escobedo",
"Valle Del Canada, General Escobedo",
"Villas de Escobedo, General Escobedo",
"San Jose de los Sauces, General Escobedo",
"Los Nogales, General Escobedo",
"Privadas de San Ángel, General Escobedo",
"Bosques de Escobedo, General Escobedo",
"Hacienda de Anáhuac I, General Escobedo",
"Zona Industrial, General Escobedo",
"Praderas de Topo Grande, General Escobedo",
"El Centenario, General Escobedo",
"Hacienda los Ayala, General Escobedo",
"Fuentes de Juárez, Juárez",
"Residencial Santa Mónica, Juárez",
"San Juan, Juárez",
"Hacienda La Morena, Juárez",
"Campestre Monte Bello, Juárez",
"Rincón del Río, Juárez",
"Gardenias, Juárez",
"Hacienda Santa Lucia, Juárez",
"Zirandaro, Juárez",
"Las Margaritas, Juárez",
"Paseo de las Margaritas, Juárez",
"El Mirador, Juárez",
"Valle de Juárez, Juárez",
"Praderas de San Juan, Juárez",
"Infonavit Benito Juárez, Juárez",
"Lomas Del Sol, Juárez",
"Coahuila, Juárez",
"Paseo Santa Fe, Juárez",
"Los Huertos, Juárez",
"Rancho Viejo, Juárez",
"Hector Caballero Escamilla, Juárez",
"Portal de Vaquerías, Juárez",
"Riviera del Sol, Juárez",
"Villas de San Juan, Juárez",
"América Unida, Juárez",
"Santa Maria, Juárez",
"Paraje Juárez, Juárez",
"Real de San Jose, Juárez",
"Paseo Sabinal, Juárez",
"Hacienda San Benito, Juárez",
"Colinas Del Sol, Juárez",
"Garza y Garza, Juárez",
"San Juan Sector Colinas, Juárez",
"La Ciudadela Sector Villas San Juan, Juárez",
"Los Encinos, Juárez",
"Las Sabinas, Juárez",
"Monte Kristal, Juárez",
"Santa Ana, Juárez",
"Villa San Francisco, Juárez",
"Jardines de Cadereyta, Cadereyta Jiménez",
"Santa Lucia, Cadereyta Jiménez",
"Lomas de los Pilares 1er Sector, Cadereyta Jiménez",
"La Rioja, Cadereyta Jiménez",
"Bella Vista 4to Sector, Cadereyta Jiménez",
"Cadereyta Jimenez, Cadereyta Jiménez",
"Las Norias, Cadereyta Jiménez",
"Praderas de Cadereyta, Cadereyta Jiménez",
"Alfredo V Bonfil, Cadereyta Jiménez",
"Framboyanes, Cadereyta Jiménez",
"San Moisés, Cadereyta Jiménez",
"San Isidro, Cadereyta Jiménez",
"Jardines de Capellania, Cadereyta Jiménez",
"Burócratas Municipales, Cadereyta Jiménez",
"Real de Cadereyta, Cadereyta Jiménez",
"Lomas de Los Pilares 3er Sector, Cadereyta Jiménez",
    "Bellavista, Cadereyta Jiménez"]

    const inputDireccion = document.getElementById('direccionDropdown')

direcciones.forEach(direccion => {
    inputDireccion.insertAdjacentHTML("beforeend",`<div onclick="selectedAddress('${direccion}')">${direccion}</div>`)
});